- name: Create a virtual machine from a template
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ vcenter_datacenter }}"
    validate_certs: no
    folder: "{{ cluster_name }}"
    name: "{{ vm_name }}"
    state: poweredon
    template: "{{ template_rhcos }}"
    disk:
    - size_gb: 100
      type: thin
      datastore: "{{ vcenter_datastore }}"
    hardware:
      memory_mb: "{{ vm_memory }}"
      num_cpus: "{{ vm_cpu }}"
      num_cpu_cores_per_socket: 2
      scsi: paravirtual
      hotadd_cpu: False
      hotremove_cpu: False
      hotadd_memory: False
      version: 14 # Hardware version of virtual machine
    networks:
    - name: "{{ vcenter_network }}"
      mac: "{{ vm_mac }}"
    wait_for_ip_address: no
    customvalues:
      - key: 'guestinfo.ignition.config.data'
        value: "{{ ignition_config_data }}"
      - key: 'guestinfo.ignition.config.data.encoding'
        value: 'base64'
      - key: 'disk.EnableUUID'
        value: 'TRUE'
#      - key: 'sched.cpu.latencySensitivity'
#        value: 'high'
  delegate_to: localhost
  register: deploy

